pipeline {
  agent any

  environment {
    IMAGE_NAME = "infraweb"
    DOCKERHUB_CREDENTIALS =  "dockerhub"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build Docker Image') {
      steps {
        script {
          docker.withRegistry('https://index.docker.io/v1/', 'DOCKERHUB_CREDENTIALS') {
            def app = docker.build("${IMAGE_NAME}:latest", "infra/web")
            app.push()
          }
        }
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        sh "kubectl apply -f infra/k8s/frontend_deployment.yml"
        sh "kubectl rollout restart deployment/infra-web -n app"
      }
    }
  }
}
